version: "2"

run:
  timeout: 20m

issues:
  new: true

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - depguard

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by logutils.Log, logrus is allowed only in logutils package

    dupl:
      threshold: 100

    goconst:
      min-len: 2
      min-occurrences: 2

    gocritic:
      disabled-checks:
        - wrapperFunc
      enabled-tags:
        - performance
        - style
        - experimental

    lll:
      line-length: 140

  exclusions:
    rules:
      - linters:
          - gosec
        text: weak cryptographic primitive
      - linters:
          - staticcheck
        text: "SA1019:"
    paths:
      - test/testdata_etc
      - pkg/golinters/goanalysis/(checker|passes)

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint